# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: fir3wa1k3r
email: fir3wa1k3r.sh@protonmail.com

#write html inside the double quotes to display in jumbotron
description: "<center><h2>My Security Blog</h2></center>Hope you like it!"



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hemangsk.github.io" # the base hostname & protocol for your site
twitter_username: fir3wa1k3r
github_username:  fir3wa1-k3r

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
